Fix for issue: SaveManualExecutionPicture threw exceptionjava.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.getParts()Ljava/util/Collection; at org.cerberus.servlet.manualtestcase.SaveManualExecutionPicture.doPost(SaveManualExecutionPicture.java:35) List of modifications: 1) SaveManualExecutionPicture.java: Instead of using the getParts() method that does not exist, we use the library org.apache.commons.fileupload;  additional validations: users can't upload files that exceed a certain size limit; and user can't upload files that are not images. 2) DatabaseVersioningService: max limit size for screen-shot; and 3) FileUtil: class that provides auxiliary methods related to files.